# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/singleCycleCpu/singleCycleCpu.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/singleCycleCpu/singleCycleCpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/ExtendSa.v
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/SignZeroExtend.v
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/Select5.v
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/Select32.v
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/RegisterFile.v
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/PC.v
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/NextPC.v
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/JumpPC.v
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/InstructionMemory.v
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/DataMemory.v
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/ControlUnit.v
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/ALU.v
  C:/Users/Administrator/singleCycleCpu/singleCycleCpu.srcs/sources_1/new/SingleCycleCpu.v
}
synth_design -top SingleCycleCPU -part xc7a35tcpg236-1
write_checkpoint -noxdef SingleCycleCPU.dcp
catch { report_utilization -file SingleCycleCPU_utilization_synth.rpt -pb SingleCycleCPU_utilization_synth.pb }
